<div class="main-content">
    <div class="wrapper">
    <h1>Add Category</h1>
    
    <?php
        // list of all session variables to print, depending on the situation
        $session_var =  array('add', 'upload');
        foreach ($session_var as $s ) {
            if(isset($_SESSION[$s])) {
                echo $_SESSION[$s];
                unset($_SESSION[$s]);
            }
        }
    ?>
            

    <!-- Add category form starts -->
    <form action="index.php?road=addCategory" method="POST" enctype="multipart/form-data">
        <table class="tbl-30">
            <tr>
                <td> Title: </td>
                <td>
                    <input type="text" name="title" placeholder= "Category Title" required>
                </td>
            </tr>
             <tr>
                <td> Select Image: </td>
                <td>
                    <input type="file" name="image" required>
                </td>
            </tr>
            <tr>
                <td> Featured: </td>
                <td>
                    <input type="radio" name="featured" value="Yes"> Yes 
                    <input type="radio" name="featured" value="No"> No
                </td>
            </tr>
            <tr>
                <td> Active: </td>
                <td>
                    <input type="radio" name="active" value="Yes"> Yes
                    <input type="radio" name="active" value="No"> No
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="submit" name="submit" value="Add Category" class="btn-secondary">
                </td>
            </tr>
        </table>
    </form>
    </div>
</div>
