<div class="main-content">
    <div class="wrapper">
    <h1>Add Collection</h1>
    
    <?php
        // list of all session variables to print, depending on the situation
        $session_var =  array('add', 'upload');
        foreach ($session_var as $s ) {
            if(isset($_SESSION[$s])) {
                echo $_SESSION[$s];
                unset($_SESSION[$s]);
            }
        }
    ?>
    
    <!-- add collection form -->
    <form action="index.php?road=addCollection" method="POST" enctype="multipart/form-data">
        <table class="tbl-30">
            <tr>
                <td> Title: </td>
                <td>
                    <input type="text" name="title" placeholder= "Collection Title" required>
                </td>
            </tr>
            <tr>
                <td>Description:</td>
                <td>
                    <textarea name="description" cols="30" rows="5" placeholder="Description of collection"/> </textarea>
                </td>
            </tr>
            <tr>
                <td>Price:</td>
                <td>
                    <input type="number" name="price" min="0" required>
                </td>
            </tr>        
            <tr>
                <td> Select Image: </td>
                <td>
                    <input type="file" name="image" required>
                </td>
            </tr>
             <tr>
                <td>Category: </td>
                <td>
                    <select name="category">
                        <?php foreach($data as $value) :?>
                             <option value="<?= $value['title']?>"><?= $value['title']?></option>
                        <?php endforeach ?>
                        <?php if (count($data) == 0) : ?>
                            <option value="0">No Category Found</option>
                        <?php endif ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td> Featured: </td>
                <td>
                    <input type="radio" name="featured" value="Yes"> Yes 
                    <input type="radio" name="featured" value="No"> No
                </td>
            </tr>
            <tr>
                <td> Active: </td>
                <td>
                    <input type="radio" name="active" value="Yes"> Yes
                    <input type="radio" name="active" value="No"> No
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="submit" name="submit" value="Add Collection" class="btn-secondary">
                </td>
            </tr>
        </table>
    </form>
    </div>
</div>