<!-- Main content section starts -->
<div class="main-content">
    <div class="wrapper">
        <h1>Manage Orders</h1>
    </div>

    <!--button to add admin -->

    <table class="tbl-full">
        <tr>
            <th>Article Name</th>
            <th>Article Price</th>
            <th>Quantity</th>
            <th>Order Date</th>
            <th>Status</th>
            <th>Customer Name</th>
            <th>Customer Email</th>
            <th>Customer Address</th>
            <th>Action</th>
        </tr>
                
        <!--a loop over all categories to be printed in the table-->
        <?php foreach($data as $value) :?>        
            <tr>
                <td><?= $value['article_name'] ?></td>
                <td><?= $value['article_price'] ?></td>
                <td><?= $value['quantity'] ?></td>
                <td><?= $value['order_date'] ?></td>
                <td><?= $value['status'] ?></td>
                <td><?= $value['customer_name'] ?></td>
                <td><?= $value['customer_email'] ?></td>
                <td><?= $value['customer_address'] ?></td>
                <td>
                    <a href="index.php?road=goUpdateOrder&id=<?=$value['id']?>" class="btn-secondary">Modify Order</a>
                    <a href="index.php?road=deleteOrder&id=<?=$value['id']?>" class="btn-danger">Delete Order</a>
                </td>
            </tr>
        <?php endforeach?>
    </table>
</div>
<!-- Main content section ends -->
        