<head>
    <title>Bali Earth Soul Jewelry- Home Page</title>
    <link rel="stylesheet" href="../public/css/admin.css">
</head>
    
    
<!-- Menu section starts -->
<div class="menu text-center">
    <div class="wrapper">
        <ul>
            <li><a href="index.php?road=home">Home</a></li>
                <li><a href="index.php?road=manageAdmin">Admin Manager</a></li>
                <li><a href="index.php?road=manageCategory">Categories</a></li>
                <li><a href="index.php?road=manageCollection">Collections</a></li>
                <li><a href="index.php?road=manageOrder">Orders</a></li>
                <li><a href="index.php?road=logout">Logout</a></li>
        </ul>
    </div>
</div>
<!-- Menu section ends -->
        