<div class="main-content">
        <div class="wrapper">
            <h1>Update Password</h1>
            <?php
                if(isset($_SESSION['updatepwd'])) {
                    echo $_SESSION['updatepwd'];
                    unset($_SESSION['updatepwd']);
                }
            ?>
            <form action="index.php?road=updatePassword" method="POST">
                <table class="tbl-30">
                    <tr>
                        <td>Old Password:</td>
                        <td>
                            <input type="password" name="old_pwd" required>
                        </td>
                    </tr>
                    
                    <tr>
                        <td>New Password:</td>
                        <td><input type="password" name="new_pwd" required minlength="6">
                        </td>
                    </tr>
                    
                    <tr>
                        <td>Confirm New Password:</td>
                        <td><input type="password" name="new_pwd_confirm" required minlength="6">
                        </td>
                    </tr>
                    
                    <tr>
                        <td colspan="2">
                            <input type="hidden" name="id" value="<?= $id ?>">
                            <input type="submit" name="submit" value="Update Password" class="btn-secondary">
                        </td>
                    </tr>
                </table>
            </form>
        </div>
</div>
