<div class="cart-order">
    <div class="shopping">
        <h1>Shopping Cart</h1>
    </div>
    
    <?php
    // Order validation message
    if(isset($_SESSION['order'])) {
        echo $_SESSION['order'];
        unset($_SESSION['order']);
    }
    
    // if session variable exists: if something is in the cart
    if(isset($_SESSION["cart"])) :
        $total_quantity = 0;
        $total_price = 0;
    ?>	
    
        <!--Empty cart button-->
        <a href="index.php?road=emptyCart">  <button class="btnEmptyCart">Empty Cart</button></a>
        
        <!--Cart table-->
        <div class="flex-table">
            <div></div>
            <div><strong>Name</strong></div>
            <div><strong>Quantity</strong></div>
            <div><strong>Unit Price</strong></div>
            <div><strong>Price</strong></div>
            <div></div>
        </div>
        
            <?php foreach ($data as $item):?>
            	<?php $item_price = $item["quantity"]*$item["article_price"]; ?>
            
                <div class="flex-table">
                    <div>
                        <?php if($item['article_image'] != "") : ?>
                        <img src="../public/img/collection/<?=$item['article_image']?>">
                    <?php 
                    else :
                        echo "No Image added";
                    endif
                    ?>
                    </div>
                    <div><?= $item["article_name"] ?></div>
                    <div>
                        <a href="index.php?road=downQty&id=<?= $item["article_id"] ?>">-</a>
            			<a><?=$item["quantity"]?></a>
                        <a href="index.php?road=upQty&id=<?= $item["article_id"] ?>">+</a>
                    </div>
                    <div><?= "$ ".$item["article_price"]?><input type='hidden' value=<?= $item["article_price"]?>></div>
                    <div><?= "$ ". number_format($item_price,2)?></div>
                    <div>
                        <a href="index.php?road=removeCart&id=<?= $item["article_id"] ?>" class="btnRemoveItem"><img src="icon-delete.png" alt="Remove Item" /></a>
                    </div>
                </div>
            		<?php
            		// add to total quantity and price
            		    $total_quantity += $item["quantity"];
            			$total_price += ($item["article_price"]*$item["quantity"]);
            		?>
            <?php endforeach?>
            
            <div class="flex-table">
                <div>Total: <?= $total_quantity ?></div>
                <div><strong><?php echo "$ ".number_format($total_price, 2); ?></strong></div>
            </div>

        
        <!--validate order button-->
        <a href="index.php?road=getCommanderDetails">  <button class="btn-secondary" >Validate Order</button>
    
    
    <?php
    // if cart is empty
    else :
    ?>
        <div class="no-records">Your cart is still empty! Please take a look our collections to add it here.</div>
    <?php 
    endif
    ?>
</div>

<!--js for cart-->
<script src="../public/js/cart.js"></script>        





