<div class="search">
    <label for="search">Search:</label>
    <input type="text" id="search">
</div>    


<section class="jewelry-collection" id="target">
    <div class="container">
        <h2 class="text-center">Explore Collections</h2>
        <!--a loop over all collections to be printed in the table-->
            <?php foreach($col as $value) :?>
            <form action="index.php?road=addCart&id=<?=$value['id']?>" method="POST">
                    
                <div class="jewelry-collection-box">
                    <?php if($value['image_name'] != "") : ?>
                        <div class="jewelry-collection-img">
                            <img src="../public/img/collection/<?=$value['image_name']?>" alt=<?=$value['title']?> class="img-responsive img-curve" >
                        </div>
                    <?php 
                        else :  
                            echo "No Image added";
                        endif
                    ?> 
                    <div class="jewelry-collection-desc">
                        <h4> <?= $value['title'] ?></h4>
                        <p class="jewelry-price"><?= $value['price'] ?></p>
                        <p class="jewelry-detail"><?= $value['description'] ?></p>
                        <input type="hidden" name="prod_id" value="<?= $value['id'] ?>">
                        <input type="number" class="product-quantity" name="quantity" value="1" min="1">
                        <input type="submit" name="add_to_cart" value="Add to cart" class="btn btn-primary">
                    </div>
                </div>
            </form>
            <?php endforeach?>
    </div>
</section>

<div class="clearfix"></div>



