<!--navbar social media start-->
<section class="social">
    <div class="container text-center">
        <ul>
            <li>
                <a href="#" class="fa fa-facebook"></a>
            </li>
            <li>
                <a href="#" class="fa fa-twitter"></a>
            </li>
            <li>
                <a href="#" class="fa fa-instagram"></a>
            </li>
        </ul>
    </div>
</section>
<!--navbar social media end-->
    
<!--navbar footer start-->
<section class="footer">
    <div class="container text-center">
        <p> ©2022 created by Yunita Bali Handmade Jewelry Team </p>
    </div>
</section>
<!--navbar footer end-->
