<div class="main-content">
    <div class="wrapper">
        <h1>Shipping Details</h1>
                
        
        <form action="index.php?road=validateCart" method="POST">
            <div class="field">
                <label for="fullname">Full Name:</label>
                <input type="text" id="fullname" name="fullname" required  value=<?= $data["name"]?>>
            </div>
            
            <div class="field">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" pattern=".+@.+.."  required/> 
            </div>
        
    
            <div class="field">
                <label for="shipAdress">Shipping Address</label>
                <input type="text" id="shipAdress" name="shipAdress" placeholder="Full address for shipping." required/>
            </div> 
            
            <div class="field">
                <input type="submit" name="submit" value="Finalize My Order" class="btn-secondary">
            </div> 
         
        </form>
    </div>
</div>

