<?php
// login message
    if(isset($_SESSION['login'])) {
        echo $_SESSION['login'];
        unset($_SESSION['login']);
    }
?>

<form action="index.php?road=login" method="post">
    <div class="field">
        <label for="username">Username</label>
        <input type="text" id="username" placeholder="Enter Username" name="username" required>
    </div> 
    
    <div class="field">
        <label for="password">Password</label>
        <input type="password" id="password" placeholder="Enter Password" name="password" required>
    </div>
    
    <div class="field">
        <button class="btn btn-primary" name="login">Login</button>
    </div>
</form> 
<!--button to go to register-->
<a href="index.php?road=goRegister"><button class="btn btn-primary form-control" name="register">Go to register</button></a>





