<?php
// login message
    if(isset($_SESSION['login'])) {
        echo $_SESSION['login'];
        unset($_SESSION['login']);
    }
?>

<!--registration form-->
<form action="index.php?road=register" method="POST">	
	<h2 class="text-register">New here? Register your account to purchase your favorite item!</h2>
	<div class="field">
		<label for="firstname">Firstname:</label>
		<input type="text" id="firstname" name="firstname" required />
	</div>

	<div class="field">
		<label for="lastname">Lastname</label>
		<input type="text" id="lastname" name="lastname" required />
	</div>
	
	<div class="field">
		<label for="username">Username</label>
		<input type="text" id="username" name="username" required/>
	</div>
	
	<div class="field">
		<label for="email">Email</label>
		<input type="email" id="email" name="email" pattern=".+@.+.."  required/> 
	</div>
	
	<div class="field">
		<label for="password">Password</label>
		<input type="password" id="password" name="password" required minlength="6"/>
	</div>
	
	<div class="field">
		<button class="btn btn-primary form-control" name="register">Register</button>
	</div>
</form>

<!--button to go to login-->
<a href="index.php?road=goLogin"><button class="btn btn-primary">Go to login</button></a>


   
  
            